name: Dotfiles CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [main]

jobs:
  dotfiles-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4

      - name: init.
        continue-on-error: true
        run: make init

      - name: brew.
        continue-on-error: true
        run: make brew

      - name: link.
        continue-on-error: true
        run: make link

      - name: defaults.
        continue-on-error: true
        run: make defaults
