name: Dotfiles CI

on:
  push:
    branches: [main]

jobs:
  dotfiles-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: init.
        continue-on-error: true
        run: make init

      - name: brew.
        continue-on-error: true
        run: make brew

      - name: link.
        continue-on-error: true
        run: make link

      - name: defaults.
        continue-on-error: true
        run: make defaults
