name: Dotfiles CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [main]

jobs:
  init:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4
      - name: init.
        run: make init

  brew:
    runs-on: macos-latest
    needs: init
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4
      - name: brew.
        run: make brew
      - name: Restore Homebrew packages
        uses: actions/cache@v2
        with:
          path: brew_packages.txt
          key: ${{ runner.os }}-brew-${{ hashFiles('brew_packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-brew-
      - name: Cache Homebrew packages
        uses: actions/cache@v2
        with:
          path: brew_packages.txt
          key: ${{ runner.os }}-brew-${{ hashFiles('brew_packages.txt') }}

  link:
    runs-on: macos-latest
    needs: init
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4
      - name: link.
        run: make link
