name: Test Dotfiles Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-dotfiles:
    runs-on: macos-latest # macOS のみで実行

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Homebrew cache
        uses: actions/cache@v3
        with:
          path: /usr/local/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile*') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Install Homebrew and packages
        run: |
          chmod +x install_brew.sh
          ./install_brew.sh

      - name: Run setup script
        run: |
          chmod +x setup.sh setup_links.sh
          ./setup.sh

      - name: Verify symlinks
        run: |
          test -L "$HOME/.zshrc" && echo ".zshrc symlink exists" || echo ".zshrc symlink does not exist"
          test -L "$HOME/.zsh" && echo ".zsh symlink exists" || echo ".zsh symlink does not exist"

      - name: Verify Zsh loads correctly
        run: |
          zsh -c "echo 'Zsh loaded successfully'"
